// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVV7dVXPIxUEnYk1gLpGwEMeTQddhi9xc',
    appId: '1:655786538944:web:0ac9896c488d5614323a25',
    messagingSenderId: '655786538944',
    projectId: 'orgtrack-6ecf3',
    authDomain: 'orgtrack-6ecf3.firebaseapp.com',
    storageBucket: 'orgtrack-6ecf3.firebasestorage.app',
    measurementId: 'G-TWGPXHNHFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkF-nMdtDgfxtEHYYwc2LFcVXWHU07D3Y',
    appId: '1:655786538944:android:7ef770df156e9fdd323a25',
    messagingSenderId: '655786538944',
    projectId: 'orgtrack-6ecf3',
    storageBucket: 'orgtrack-6ecf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_mhv1NVuhYHqWcAv5mFrfNzMNz56du4',
    appId: '1:655786538944:ios:1acf851cb8073d4f323a25',
    messagingSenderId: '655786538944',
    projectId: 'orgtrack-6ecf3',
    storageBucket: 'orgtrack-6ecf3.firebasestorage.app',
    iosBundleId: 'com.example.kelompok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS_mhv1NVuhYHqWcAv5mFrfNzMNz56du4',
    appId: '1:655786538944:ios:1acf851cb8073d4f323a25',
    messagingSenderId: '655786538944',
    projectId: 'orgtrack-6ecf3',
    storageBucket: 'orgtrack-6ecf3.firebasestorage.app',
    iosBundleId: 'com.example.kelompok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVV7dVXPIxUEnYk1gLpGwEMeTQddhi9xc',
    appId: '1:655786538944:web:ed7558567d2f92d7323a25',
    messagingSenderId: '655786538944',
    projectId: 'orgtrack-6ecf3',
    authDomain: 'orgtrack-6ecf3.firebaseapp.com',
    storageBucket: 'orgtrack-6ecf3.firebasestorage.app',
    measurementId: 'G-YEMSZ5D5ZE',
  );
}
